on:
  push:
    branches:
      - 'main'
  schedule:
    - cron: "00 06 * * ?"

jobs:
  mirror_job:
    runs-on: ubuntu-latest
    name: Mirror SOURCE_BRANCH_NAME branch to DESTINATION_BRANCH_NAME branch
    steps:
    - name: Mirror action step
      id: mirror
      uses: google/mirror-branch-action@v1.0
      with:
        github-token: ${{ secrets.TOKEN }}
        source: 'main'
        dest: 'feature'
